site_name: Digital Electronics
site_description: 'Website content for a college course in digital electronics with MicroSims. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/digital-electronics'
repo_url: 'https://github.com/dmccreary/digital-electronics'

nav:
  - Home: index.md
  - About: about.md
  - Lessons:
    - Introduction: lessons/index.md
    - Boolean Algebra: lessons/boolean-algebra.md
    - Logic Gates: lessons/logic-gates.md
  - Sims:
    - Introduction: sims/index.md
    - Logic Gates: sims/logic-gates/index.md
    - Drawing Gates: sims/logic-gates/01-drawing-gates.md
    - Flip-flop: sims/flip-flop/index.md
    - Shift Register: sims/shift-register/index.md
  - Learning Graph:
    - Introduction: learning-graph/index.md
    - Course Description Assessment: learning-graph/course-description-assessment.md
    - Concept List: learning-graph/concept-list.md
    - Concept Taxonomy: learning-graph/concept-taxonomy.md
    - Quality Metrics: learning-graph/quality-metrics.md
    - Taxonomy Distribution: learning-graph/taxonomy-distribution.md
  - Glossary: glossary.md
  - License: license.md
  - How we built this site: how-we-built-this-site.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  extra_css:
    - styles/custom.css
  # logo: img/my-icon.png
  # favicon: img/my-icon.png
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX